### PR TITLE
Fixed price Kamino/Drift

### LINKED ISSUE #484: Fixed prices with kamino/drift/etc
Reminder to contributors: Please base off the latest version branch, and target the consolidated update with your PR, not main. The main branch reflects the latest version on mainnet, and may be 1-2 months stale compared to what's in active developement. Right now, that's 0.1.8-main, and https://github.com/mrgnlabs/marginfi-v2/pull/493

# Summary 

While the fixed-price feature "works" for Kamino/Drift/etc, it doesn't account for interest that accumulates on those banks, which makes it impractical. We should have a fixed-price oracle type for those asset types that (1) fixes the "base" price that we normally get from Pyth/Swb/etc, (2) continues to multiply by the exchange rate for that venue's underlying Reserve/Market/etc.

### PR DESCRIPTION
**Pull request by jgur-psyops**
Likely needs audit in 1.8

## Summary

Closes #484 

Adds support for Fixed prices in Kamino/Drift banks. Major refactor of functions in price.rs. Adds tests for Fixed-price functionality.

### Breaking change
`lending_pool_set_fixed_oracle_price` [now expects integration "oracles"](https://github.com/mrgnlabs/marginfi-v2/pull/496/changes#diff-0b4bcb97cd3d20c81c66abe4b4928d9bdf7997119bed36d4e53ae57e1a5fa422R56) (reserve - for Kamino, spot market - for Drift) in `remaining_accounts` so that it can set the proper `OracleSetup` right away, without the need to call `lending_pool_configure_bank_oracle` afterwards. Regular banks do not require passing any remaining accounts, as before.

Thanks to https://github.com/AadityaAnand for starting the feature

### CODE REVIEW

File: programs/marginfi/src/state/price.rs [hunk 1]
```diff
@@ -182,29 +256,13 @@ impl OraclePriceFeedAdapter {
...
-                    // * Note: Typically price updates are owned by `pyth_solana_receiver_sdk` and the oracle
-                    // feed account itself is owned by PYTH ID. On localnet, the mock program may own both for
-                    // simplicity.
-                    let owner_ok = account_info.owner.eq(&PYTH_ID)
-                        || account_info.owner.eq(&pyth_solana_receiver_sdk::id());
-                    check!(owner_ok, MarginfiError::StakedPythPushWrongAccountOwner);
-                }
+                check_primary_oracle_key(bank_config, account_info)?;
 
+                // On localnet, allow the mock program ID OR the real one (for regression tests against
```
Comment (IliaZyrin) [inline programs/marginfi/src/state/price.rs]: The comment is no longer relevant since you removed the respective logic.

File: type-crate/src/types/bank.rs [hunk 2]
```diff
@@ -208,6 +210,8 @@ impl OracleSetup {
             10 => Some(Self::DriftSwitchboardPull),
             11 => Some(Self::SolendPythPull),
             12 => Some(Self::SolendSwitchboardPull),
+            14 | 15 => Some(Self::FixedKamino),
```
Comment (jgur-psyops) [inline type-crate/src/types/bank.rs]: 15 should be FixedDrift and this should just be 14: Kamino 15: Drift rather than 14 | 15 Kamino

Comment (jgur-psyops) [inline type-crate/src/types/bank.rs]: 13 (and Drift 14)

File: programs/marginfi/src/state/price.rs [hunk 3]
```diff
@@ -574,6 +463,73 @@ impl OraclePriceFeedAdapter {
...
                 Ok(OraclePriceFeedAdapter::SwitchboardPull(price_feed))
             }
+            OracleSetup::FixedDrift => {
+                // Fixed base price + Drift spot market exchange rate
+                // Requires: Drift spot market (no oracle needed)
+                check!(ais.len() == 1, MarginfiError::WrongNumberOfOracleAccounts);
+
+                let spot_market_info = &ais[0];
+
+                let spot_market_loader = load_drift_spot_market(bank_config, spot_market_info)?;
```
Comment (jgur-psyops) [inline programs/marginfi/src/state/price.rs:473]: Just to document this for future reference: we actually don't have to check Reserve/SpotMarket for Drift or Kamino banks because they enforce reserve/market validation when they are first created, they cannot be created with a FixedPrice, and the reserve/market they are created with can never change.

Nonetheless, a sanity check is always welcome, in case any of the above ever ceases to be accurate!
